
**INSTALLATION**

In [1]:
## importing numpy
import numpy as np

In [2]:
## checking version
print(np.__version__)


1.26.4


**CREATING ARRAY**

In [3]:
## creating numpy nd array
## using list
arr=np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [4]:
## using tuple
arr=np.array((1,2,3,4,5,6))
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


**DIMENSION**


In [5]:
## 0D array
arr=np.array(10)
print(arr)
print("number of dimensions is",arr.ndim)
## 1d array
arr=np.array([10,20,30,40,50])
print(arr)
print(type(arr))
print("number of dimensions is",arr.ndim)



10
number of dimensions is 0
[10 20 30 40 50]
<class 'numpy.ndarray'>
number of dimensions is 1


In [6]:
## 2d array
arr=np.array([[1,2],[3,4]])
print(arr)
print("number of dimensions is",arr.ndim)

[[1 2]
 [3 4]]
number of dimensions is 2


In [7]:
##3d array
arr=np.array([[[1,2],[3,4],[5,6]]])
print(arr)
print("number of dimensions is",arr.ndim)

[[[1 2]
  [3 4]
  [5 6]]]
number of dimensions is 3


**ACCESS ARRAY ELEMENTS**

In [8]:
arr=np.array([[1,2],[3,4]])
print(arr[0,1])

2


In [9]:
arr=np.array([10,20,30,40,50])
print(arr[1])

20


In [10]:
arr=np.array([[[1,2],[3,4],[5,6]]])
print(arr[0,1,0])

3


In [11]:
## negative indexing
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,-1])

10


**SLICING ARRAY**


In [12]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[1:5])

[2 3 4 5]


In [13]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr[4:])

[ 5  6  7  8  9 10 11 12]


In [14]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr[-5:-1])

[ 8  9 10 11]


In [15]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr[1:8:2])

[2 4 6 8]


In [16]:
## 2d array
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr[0,2:])

[3 4 5 6]


**DATA TYPE**

In [17]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.dtype)

int32


In [18]:
arr=np.array(["apple","cherry"])
print(arr.dtype)

<U6


**CREATING ARRAY WITH DEFINED DATA TYPE**

In [19]:
## with string
arr=np.array([1,2,3,4,5],dtype="S")
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [20]:
## with int
arr=np.array([1,2,3,4,5],dtype="i4")
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


**DIFFRENCE BETWEEN COPY AND VIEW**
* copy is the new array 
* view is just the view of original array

In [76]:
## copy
arr=np.array([1,2,3,4,5])
x=arr.copy()
print(arr)
print(x)
## copy is not affected if make changes in original array
arr[0]=10
print(arr)

[1 2 3 4 5]
[1 2 3 4 5]
[10  2  3  4  5]


In [22]:
## view
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=10
print(arr)
print(x)

[10  2  3  4  5]
[10  2  3  4  5]


In [23]:
arr=np.array([1,2,3,4,5])
x=arr.view()
x[0]=10
print(arr)
print(x)
## original array is affected if changes is made in view

[10  2  3  4  5]
[10  2  3  4  5]


**SHAPE OF ARRAY**
* no. of elements  in each dimension is called shape of the array

In [24]:
arr=np.array([[1,2],[3,4]])
print(arr.shape)

(2, 2)


In [25]:
arr=np.array([1,2,3,4],ndmin=5)
print("The shape of array is",arr.shape)


The shape of array is (1, 1, 1, 1, 4)


**RESHAPING ARRAY**
* Changing shape of the array


In [26]:
##1d to 2d
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1=arr.reshape(4,3)
print(arr1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:
## 1d to 3d 
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1=arr.reshape(2,3,2)
print(arr1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


We can reshape only in those dimension whose multiplication is equal to the shape of array


In [28]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1=arr.reshape(2,3,2)
print(arr1.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


**UNKNOWN DIMENSION**
* we can specify -1 as one dimension in reshape method
* -1 can be passed not for more than 1 dimension


In [29]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1=arr.reshape(2,-1)
print(arr1)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


**FLATTENING THE ARRAYS**

* Converting multi dimensional array into 1d array
* reshape(-1) is used 

In [30]:
arr=np.array([[1,2],[3,4]])
arr1=arr.reshape(-1)
print(arr1)

[1 2 3 4]


In [31]:
arr=np.array([[[1,2],[3,4],[5,6]]])
arr1=arr.reshape(-1)
print(arr1)

[1 2 3 4 5 6]


**ITERATING ARRAYS**

* going through elements one by one


In [32]:
##1d array
arr=np.array([1,2,3,4,5,6,7,8])
for x in arr:
    print(x)

1
2
3
4
5
6
7
8


In [33]:
## 2d array
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [34]:
##3d array
arr=np.array([[[1,2],[3,4],[5,6]]])
for x in arr:
    print(x)

[[1 2]
 [3 4]
 [5 6]]


In [35]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


**ITERATING ARRAYS USING nditer()**

In [36]:
arr=np.array([[[1,2],[3,4],[5,6]]])
for x in np.nditer(arr):
   print(x)

1
2
3
4
5
6


**ITERATING ARRAY WITH DIFFRENT DATA TYPES**

* op_dtypes argument is used and pass the expected datatype to change the datatype of elements while iterating
* Numpy does not change the data type of element in place  so it needs some another place to perform this action , this extra space is called **buffer** .In order to enable it in nditer(),we pass **flags=["buffered"]**

In [37]:
## iterate through array as string
arr=np.array([1,2,3,4,5])
for x in np.nditer(arr,flags=["buffered"],op_dtypes="S"):
      print(x)

b'1'
b'2'
b'3'
b'4'
b'5'


**ITERATING ARRAY WITH DIFFRENT STEP SIZE**


In [38]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
7


**ENUMERATED ACTION USING ndenumerate()**
* Enumeration means mentioning sequence number of something one by one
* ndenumerate() method can be used in cases where we want  corresponding index of element while iterating

In [75]:
arr=np.array([1,2,3,4])
for x in np.ndenumerate(arr):
    print(idx,x)

(1, 3) ((0,), 1)
(1, 3) ((1,), 2)
(1, 3) ((2,), 3)
(1, 3) ((3,), 4)


In [40]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


**JOINING NUMPY ARRAYS**
* Putting contents of two or more arrays in single array
* In Numpy ,arrays are joined by axes
* **concatenate()** function is used
* **stack()** function is used

In [41]:
##1d array
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [42]:
## 2d array
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2))
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


**JOINING  BY stack() FUNCTION**
* stacking is done along new axis

In [43]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


**BY hstack()**
* stack along rows

In [44]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


**BY vstack()**

* stack along columns

In [45]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


**BY dstack()**

* stack along depth(height)

In [46]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


**SPLITTING NUMPY ARRAYS**
* Spliting is reverse operation of joining
* breaks one array into multiple

**array_split()**
* return value is an array containing each split as an array
* It automatically adjusts the elements when elements are less in source array


In [47]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr1=np.array_split(arr,3)
print(arr1)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [48]:
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
arr1=np.array_split(arr,3)
print(arr1)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


**hsplit()**

In [49]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
arr1=np.hsplit(arr,3)
print(arr1)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


**vsplit()** and **dsplit()** can be used similarly

**SEARCHING ARRAYS**

In [50]:
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr==5)
print(x)
## returns the index of element

(array([4], dtype=int64),)


In [51]:
## searching for even values
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [52]:
## searching for odd values
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2!=0)
print(x)

(array([0, 2, 4, 6], dtype=int64),)


**searchsorted() METHOD** 

In [53]:
arr=np.array([1,2,3,4,5,6])
x=np.searchsorted(arr,4)
print(x)

3


In [54]:
## search from right side
arr=np.array([5,6,7,8])
x=np.searchsorted(arr,6,side="right")
print(x)

2


In [55]:
## Multiple values
arr=np.array([1,2,3,4,5,6,7,8])
x=np.searchsorted(arr,[2,4,6])
print(x)

[1 3 5]


**SORTING ARRAYS**
* Putting elements in an ordered sequence
* **sort()** is used
* returns a copy of the array ,leaving the original array unchanged

In [56]:
arr=np.array([15,687,42,10,356,258])
print("The original array is ",arr)
print("The sorted array is ",np.sort(arr))

The original array is  [ 15 687  42  10 356 258]
The sorted array is  [ 10  15  42 258 356 687]


In [57]:
## alphabetically sorting
arr=np.array(["cherry","apple","banana",])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [58]:
## sort boolean array
arr=np.array([True,False,True])
print(np.sort(arr))

[False  True  True]


**FILTERING ARRAYS**
* Get some elements out of the existing array and creating a new array out of them is called filtering

In [59]:
arr=np.array([41,42,43,44,45,46,47])
x=[True,False,True,True,False,True,True]
arr1=arr[x]
print(arr1)

[41 43 44 46 47]


**CREATING THE FILTERING ARRAY**


In [60]:
arr=np.array([41,42,43,44,45,46,47])
## creating empty list
filter_arr=[]
for i in arr:
    if i>43:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
arr1=arr[filter_arr]
print(filter_arr)
print(arr1)

[False, False, False, True, True, True, True]
[44 45 46 47]


In [61]:
## for even number filtering
arr=np.array([41,42,43,44,45,46,47])
## creating empty list
filter_arr=[]
for i in arr:
    if i%2==0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
arr1=arr[filter_arr]
print(filter_arr)
print(arr1)

[False, True, False, True, False, True, False]
[42 44 46]


**CREATING FILTER DIRECT FROM ARRAY**

In [62]:
arr=np.array([41,42,43,44,45,46,47])
filter_arr=arr>43
arr1=arr[filter_arr]
print(filter_arr)
print(arr1)

[False False False  True  True  True  True]
[44 45 46 47]


**RANDOM NUMBERS**

In [66]:
## generating a random number
from numpy import random
x=random.randint(100)
print(x)

56


In [67]:
## generate random float
x=random.rand()
print(x)

0.011890432984270394


In [68]:
## generating random array
x=random.randint(100,size=(5))
print(x)

[25 57 14 54 74]


In [69]:
x=random.randint(100,size=(3,6))
print(x)

[[63 66  5 58 91 50]
 [31 44 35 26 11 71]
 [96 34 55 82 41 57]]


In [73]:
from numpy import random
x=random.rand(5)
print(x)

[0.877512   0.25392145 0.60652405 0.64977097 0.8826299 ]


In [74]:
from numpy import random
x=random.rand(3,4)
print(x)

[[0.95334456 0.65767003 0.39922549 0.54522056]
 [0.62160395 0.31289792 0.87268331 0.87954116]
 [0.38819704 0.87215179 0.42520862 0.07024706]]


**GENERATE RANDOM NUMBER FROM ARRAY**
* **choice()** method return an array of values
* **size()** parameter is used  t o specify the shape of array

In [77]:
x=random.choice([3,5,7,9])
print(x)

5


In [78]:
x=random.choice([3,5,7,9],size=(3,5))
print(x)

[[9 7 3 5 7]
 [3 7 5 3 3]
 [5 5 9 3 9]]
